
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const SUGGESTIONS_CLEAR = 'SUGGESTIONS_CLEAR';
export const SUGGESTIONS_UPDATE = 'SUGGESTIONS_UPDATE';
export const SUGGESTIONS_LOAD = 'SUGGESTIONS_LOAD';
